package defpackage;

import a.bx;
import a.du;
import java.util.UUID;
import okhttp3.internal.http.StatusLine;

/* loaded from: classes2.dex */
public abstract class t60 {
    public static final String A;
    public static final String B;
    public static final String C;
    public static final String D;
    public static final String E;
    public static final String F;
    public static final String G;
    public static final String H;

    /* renamed from: a, reason: collision with root package name */
    public static final String f4456a;

    /* renamed from: b, reason: collision with root package name */
    public static final String f4457b;
    public static final String c;
    public static final String d;
    public static final String e;
    public static final String f;
    public static final String g;
    public static final String h;
    public static final String i;
    public static final String j;
    public static final String k;
    public static final String l;
    public static final String m;
    public static final String n;
    public static final String o;
    public static final String p;
    public static final String q;
    public static final String r;
    public static final String s;
    public static final String t;
    public static final String u;
    public static final String v;
    public static final String w;
    public static final String x;
    public static final String y;
    public static final String z;

    static {
        bx i2 = hx2.i(224);
        i2.u();
        i2.h();
        bx i3 = hx2.i(223);
        String u2 = i3.u();
        i3.h();
        f4456a = u2;
        bx bxVar = new bx();
        du.d(225, bxVar);
        bxVar.u();
        bxVar.h();
        UUID.randomUUID().toString();
        bx bxVar2 = new bx();
        du.d(390, bxVar2);
        String u3 = bxVar2.u();
        bxVar2.h();
        f4457b = u3;
        bx i4 = hx2.i(391);
        String u4 = i4.u();
        i4.h();
        c = u4;
        bx i5 = hx2.i(392);
        String u5 = i5.u();
        i5.h();
        d = u5;
        bx i6 = hx2.i(394);
        String u6 = i6.u();
        i6.h();
        e = u6;
        bx i7 = hx2.i(396);
        String u7 = i7.u();
        i7.h();
        f = u7;
        bx i8 = hx2.i(397);
        String u8 = i8.u();
        i8.h();
        g = u8;
        bx i9 = hx2.i(399);
        String u9 = i9.u();
        i9.h();
        h = u9;
        bx i10 = hx2.i(400);
        String u10 = i10.u();
        i10.h();
        i = u10;
        bx i11 = hx2.i(401);
        String u11 = i11.u();
        i11.h();
        j = u11;
        bx i12 = hx2.i(402);
        String u12 = i12.u();
        i12.h();
        k = u12;
        bx i13 = hx2.i(403);
        String u13 = i13.u();
        i13.h();
        l = u13;
        bx i14 = hx2.i(404);
        String u14 = i14.u();
        i14.h();
        m = u14;
        bx i15 = hx2.i(405);
        String u15 = i15.u();
        i15.h();
        n = u15;
        bx i16 = hx2.i(406);
        String u16 = i16.u();
        i16.h();
        o = u16;
        bx i17 = hx2.i(407);
        String u17 = i17.u();
        i17.h();
        p = u17;
        bx i18 = hx2.i(418);
        String u18 = i18.u();
        i18.h();
        q = u18;
        bx i19 = hx2.i(StatusLine.HTTP_MISDIRECTED_REQUEST);
        String u19 = i19.u();
        i19.h();
        r = u19;
        bx i20 = hx2.i(422);
        String u20 = i20.u();
        i20.h();
        s = u20;
        bx i21 = hx2.i(419);
        String u21 = i21.u();
        i21.h();
        t = u21;
        bx i22 = hx2.i(420);
        String u22 = i22.u();
        i22.h();
        u = u22;
        bx i23 = hx2.i(423);
        String u23 = i23.u();
        i23.h();
        v = u23;
        bx i24 = hx2.i(424);
        String u24 = i24.u();
        i24.h();
        w = u24;
        bx i25 = hx2.i(425);
        String u25 = i25.u();
        i25.h();
        x = u25;
        bx i26 = hx2.i(426);
        String u26 = i26.u();
        i26.h();
        y = u26;
        bx i27 = hx2.i(427);
        String u27 = i27.u();
        i27.h();
        z = u27;
        bx i28 = hx2.i(428);
        String u28 = i28.u();
        i28.h();
        A = u28;
        bx i29 = hx2.i(429);
        String u29 = i29.u();
        i29.h();
        B = u29;
        bx i30 = hx2.i(430);
        String u30 = i30.u();
        i30.h();
        C = u30;
        bx i31 = hx2.i(431);
        String u31 = i31.u();
        i31.h();
        D = u31;
        bx i32 = hx2.i(433);
        String u32 = i32.u();
        i32.h();
        E = u32;
        bx i33 = hx2.i(434);
        String u33 = i33.u();
        i33.h();
        F = u33;
        bx i34 = hx2.i(435);
        String u34 = i34.u();
        i34.h();
        G = u34;
        bx i35 = hx2.i(443);
        String u35 = i35.u();
        i35.h();
        H = u35;
    }
}
